// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PageNotFound: typeof import('./components/PageNotFound.vue')['default']
    TimeOfDay: typeof import('./components/TimeOfDay.vue')['default']
    WeatherDisplay: typeof import('./components/WeatherDisplay.vue')['default']
  }
}

export { }
